import type { CrmVacancyInput } from './types';

/**
 * Демонстрационный срез CRM.
 *
 * Один и тот же массив питает и `prisma db seed`, и хранилище в памяти:
 * иначе демо-режим и настоящая база расходились бы, и баг находился бы
 * только на проде.
 */

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000);

export const CRM_VACANCIES: CrmVacancyInput[] = [
  {
    crmId: 'CRM-1001',
    companyName: 'Кофейни «Север»',
    contactName: 'Анна Верещагина',
    contactEmail: 'hr@sever-coffee.ru',
    crmClientId: 'client-sever',
    title: 'Бариста',
    summary:
      'Небольшая сеть спешелти-кофеен ищет бариста на утренние и вечерние смены. Обучение на месте — опыт не нужен, нужен интерес к кофе.',
    responsibilities: [
      'Готовить эспрессо и напитки на его основе',
      'Работать на кассе и общаться с гостями',
      'Держать бар в чистоте по чек-листу смены',
    ],
    requirements: [
      'Возраст от 18 лет, медкнижка (поможем оформить)',
      'Готовность работать 3–4 смены в неделю',
      'Внимательность и спокойствие в час пик',
    ],
    perks: ['Бесплатный кофе и обеды', 'Оплата раз в две недели', 'Смены под расписание учёбы'],
    salaryFrom: 3200,
    salaryTo: 4200,
    salaryPeriod: 'SHIFT',
    city: 'Москва',
    district: 'Хамовники',
    workFormat: 'ONSITE',
    employmentType: 'SHIFT',
    shiftDays: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'],
    hoursPerWeek: 24,
    tags: ['Без опыта', 'Гибкий график', 'Питание'],
    isHot: true,
    isActive: true,
    publishedAt: daysAgo(1),
  },
  {
    crmId: 'CRM-1002',
    companyName: 'Кофейни «Север»',
    contactName: 'Анна Верещагина',
    contactEmail: 'hr@sever-coffee.ru',
    crmClientId: 'client-sever',
    title: 'Помощник управляющего кофейни',
    summary:
      'Позиция для студента старших курсов, который хочет расти в операционный менеджмент: инвентаризация, графики, приёмка.',
    responsibilities: [
      'Составлять графики смен и вести табель',
      'Принимать поставки и вести остатки',
      'Помогать управляющему с отчётностью',
    ],
    requirements: [
      '3–4 курс, экономика/менеджмент или смежное',
      'Уверенный Excel / Google Таблицы',
      'От 20 часов в неделю',
    ],
    perks: ['Наставник из управляющей команды', 'Рост до управляющего за год', 'Оплата проезда'],
    salaryFrom: 62000,
    salaryTo: 78000,
    salaryPeriod: 'MONTH',
    city: 'Москва',
    district: 'Хамовники',
    workFormat: 'ONSITE',
    employmentType: 'PART_TIME',
    shiftDays: ['MON', 'TUE', 'WED', 'THU', 'FRI'],
    hoursPerWeek: 25,
    tags: ['Карьерный рост', 'Excel', 'Менеджмент'],
    isHot: false,
    isActive: true,
    publishedAt: daysAgo(4),
  },
  {
    crmId: 'CRM-1003',
    companyName: 'Metrika Digital',
    contactName: 'Кирилл Осипов',
    contactEmail: 'people@metrika.digital',
    crmClientId: 'client-metrika',
    title: 'Ассистент таргетолога',
    summary:
      'Диджитал-агентство берёт стажёра в перформанс-отдел. Реальные бюджеты, свой пул клиентов через три месяца.',
    responsibilities: [
      'Собирать креативы и запускать тестовые кампании',
      'Вести отчётность по площадкам',
      'Анализировать связки и предлагать гипотезы',
    ],
    requirements: [
      'Понимание, как устроена реклама в соцсетях',
      'Аккуратность в цифрах',
      'От 20 часов в неделю, можно удалённо',
    ],
    perks: ['Гибрид 2/3', 'Курс по перформансу за счёт компании', 'Оффер после стажировки'],
    salaryFrom: 55000,
    salaryTo: 70000,
    salaryPeriod: 'MONTH',
    city: 'Москва',
    district: 'Белорусская',
    workFormat: 'HYBRID',
    employmentType: 'INTERNSHIP',
    shiftDays: ['MON', 'TUE', 'WED', 'THU', 'FRI'],
    hoursPerWeek: 24,
    tags: ['Маркетинг', 'Аналитика', 'Стажировка'],
    isHot: true,
    isActive: true,
    publishedAt: daysAgo(2),
  },
  {
    crmId: 'CRM-1004',
    companyName: 'Metrika Digital',
    contactName: 'Кирилл Осипов',
    contactEmail: 'people@metrika.digital',
    crmClientId: 'client-metrika',
    title: 'Контент-менеджер соцсетей',
    summary:
      'Нужен человек, который ведёт аккаунты клиентов: пишет тексты, собирает рилсы, следит за реакцией аудитории.',
    responsibilities: [
      'Готовить контент-план на неделю',
      'Монтировать вертикальные видео',
      'Отвечать в комментариях и директе',
    ],
    requirements: [
      'Грамотный русский язык',
      'CapCut или Premiere на базовом уровне',
      'Портфолио — хотя бы личный проект',
    ],
    perks: ['Полностью удалённо', 'Свободный график сдачи', 'Оплата по факту закрытия месяца'],
    salaryFrom: 48000,
    salaryTo: 60000,
    salaryPeriod: 'MONTH',
    city: 'Москва',
    district: null,
    workFormat: 'REMOTE',
    employmentType: 'PART_TIME',
    shiftDays: ['MON', 'TUE', 'WED', 'THU', 'FRI'],
    hoursPerWeek: 20,
    tags: ['Удалённо', 'SMM', 'Видео'],
    isHot: false,
    isActive: true,
    publishedAt: daysAgo(6),
  },
  {
    crmId: 'CRM-1005',
    companyName: 'Grand Plaza Hotel',
    contactName: 'Марина Долгих',
    contactEmail: 'career@grandplaza.ru',
    crmClientId: 'client-grandplaza',
    title: 'Администратор стойки размещения',
    summary:
      'Отель 4* ищет студентов на стойку. График сутки через трое — удобно совмещать с очным обучением.',
    responsibilities: [
      'Заселять и выселять гостей',
      'Вести бронирования в PMS',
      'Решать вопросы гостей на английском и русском',
    ],
    requirements: [
      'Английский от B1',
      'Опрятность и доброжелательность',
      'Готовность к ночным сменам',
    ],
    perks: ['Сутки через трое', 'Форма и питание', 'Скидки в отелях сети'],
    salaryFrom: 72000,
    salaryTo: 88000,
    salaryPeriod: 'MONTH',
    city: 'Москва',
    district: 'Тверская',
    workFormat: 'ONSITE',
    employmentType: 'SHIFT',
    shiftDays: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'],
    hoursPerWeek: 40,
    tags: ['Английский', 'Сутки/трое', 'Гостиничный бизнес'],
    isHot: false,
    isActive: true,
    publishedAt: daysAgo(3),
  },
  {
    crmId: 'CRM-1006',
    companyName: 'Grand Plaza Hotel',
    contactName: 'Марина Долгих',
    contactEmail: 'career@grandplaza.ru',
    crmClientId: 'client-grandplaza',
    title: 'Официант банкетной службы',
    summary:
      'Разовые и регулярные смены на банкетах и конференциях. Можно брать только выходные.',
    responsibilities: [
      'Сервировать залы под мероприятие',
      'Обслуживать гостей на банкете',
      'Убирать зал после мероприятия',
    ],
    requirements: ['Медкнижка', 'Опыт необязателен', 'Выносливость: смены по 8–10 часов'],
    perks: ['Оплата в день смены', 'Форма выдаётся', 'Чаевые остаются вам'],
    salaryFrom: 3500,
    salaryTo: 5200,
    salaryPeriod: 'SHIFT',
    city: 'Москва',
    district: 'Тверская',
    workFormat: 'ONSITE',
    employmentType: 'SHIFT',
    shiftDays: ['FRI', 'SAT', 'SUN'],
    hoursPerWeek: 16,
    tags: ['Выходные', 'Оплата в день смены', 'Без опыта'],
    isHot: true,
    isActive: true,
    publishedAt: daysAgo(1),
  },
  {
    crmId: 'CRM-1007',
    companyName: 'Даркстор «Ближний»',
    contactName: 'Игорь Пахомов',
    contactEmail: 'hr@blizhniy.store',
    crmClientId: 'client-blizhniy',
    title: 'Сборщик заказов',
    summary:
      'Сборка онлайн-заказов на складе у дома. Смены от 4 часов, выбираете сами в приложении.',
    responsibilities: [
      'Собирать заказы по маршрутному листу',
      'Проверять сроки годности',
      'Выкладывать товар на полки',
    ],
    requirements: ['От 18 лет', 'Медкнижка', 'Готовность к работе на ногах'],
    perks: ['Смены от 4 часов', 'Выплаты еженедельно', 'Склад в 10 минутах от метро'],
    salaryFrom: 380,
    salaryTo: 450,
    salaryPeriod: 'HOUR',
    city: 'Москва',
    district: 'Академическая',
    workFormat: 'ONSITE',
    employmentType: 'SHIFT',
    shiftDays: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'],
    hoursPerWeek: 20,
    tags: ['Почасовая оплата', 'Смены от 4 часов', 'Без опыта'],
    isHot: false,
    isActive: true,
    publishedAt: daysAgo(8),
  },
  {
    crmId: 'CRM-1008',
    companyName: 'Технопарк «Вектор»',
    contactName: 'Лидия Ким',
    contactEmail: 'jobs@vector-tech.ru',
    crmClientId: 'client-vector',
    title: 'Junior QA-инженер',
    summary:
      'Тестирование внутренних сервисов технопарка. Берём студентов ИТ-специальностей без коммерческого опыта.',
    responsibilities: [
      'Проходить тест-кейсы по веб-интерфейсам',
      'Заводить баги в трекер с воспроизведением',
      'Помогать в регрессе перед релизом',
    ],
    requirements: [
      'Понимание клиент-серверной архитектуры',
      'Базовый SQL',
      'Английский для чтения документации',
    ],
    perks: ['Гибрид, 2 дня в офисе', 'Ментор из команды', 'Оплачиваемая переработка'],
    salaryFrom: 60000,
    salaryTo: 80000,
    salaryPeriod: 'MONTH',
    city: 'Москва',
    district: 'Калужская',
    workFormat: 'HYBRID',
    employmentType: 'PART_TIME',
    shiftDays: ['MON', 'TUE', 'WED', 'THU'],
    hoursPerWeek: 24,
    tags: ['IT', 'SQL', 'Ментор'],
    isHot: true,
    isActive: true,
    publishedAt: daysAgo(2),
  },
  {
    crmId: 'CRM-1009',
    companyName: 'Технопарк «Вектор»',
    contactName: 'Лидия Ким',
    contactEmail: 'jobs@vector-tech.ru',
    crmClientId: 'client-vector',
    title: 'Специалист технической поддержки',
    summary:
      'Первая линия поддержки резидентов технопарка: доступы, оборудование, ПО. Ночных смен нет.',
    responsibilities: [
      'Принимать обращения в тикет-системе',
      'Настраивать рабочие места и доступы',
      'Вести базу знаний',
    ],
    requirements: ['Windows и macOS на уровне уверенного пользователя', 'Терпение', 'От 20 часов в неделю'],
    perks: ['График 2/2', 'Обеды в технопарке', 'Доступ к лабораториям'],
    salaryFrom: 52000,
    salaryTo: 65000,
    salaryPeriod: 'MONTH',
    city: 'Москва',
    district: 'Калужская',
    workFormat: 'ONSITE',
    employmentType: 'SHIFT',
    shiftDays: ['MON', 'TUE', 'WED', 'THU', 'FRI'],
    hoursPerWeek: 22,
    tags: ['IT', 'Поддержка', 'График 2/2'],
    isHot: false,
    isActive: true,
    publishedAt: daysAgo(9),
  },
  {
    crmId: 'CRM-1010',
    companyName: 'Образовательный центр «Логос»',
    contactName: 'Пётр Савин',
    contactEmail: 'hr@logos-edu.ru',
    crmClientId: 'client-logos',
    title: 'Преподаватель математики (подготовка к ЕГЭ)',
    summary:
      'Ведём группы 10–11 классов. Ищем студентов сильных технических вузов, которые помнят, как сами сдавали.',
    responsibilities: [
      'Вести занятия по готовой программе',
      'Проверять домашние работы',
      'Давать обратную связь родителям раз в месяц',
    ],
    requirements: [
      'Профильный ЕГЭ по математике от 80 баллов',
      'Технический вуз, 2 курс и выше',
      'Два вечера в неделю',
    ],
    perks: ['Готовые материалы', 'Оплата за час выше рынка', 'Можно вести онлайн'],
    salaryFrom: 1400,
    salaryTo: 2000,
    salaryPeriod: 'HOUR',
    city: 'Москва',
    district: 'Проспект Мира',
    workFormat: 'HYBRID',
    employmentType: 'PART_TIME',
    shiftDays: ['TUE', 'THU', 'SAT'],
    hoursPerWeek: 10,
    tags: ['Преподавание', 'Вечера', 'Высокая ставка'],
    isHot: false,
    isActive: true,
    publishedAt: daysAgo(5),
  },
  {
    crmId: 'CRM-1011',
    companyName: 'Агентство «Формат»',
    contactName: 'Юлия Нестерова',
    contactEmail: 'staff@format-events.ru',
    crmClientId: 'client-format',
    title: 'Хостес на выставки и конференции',
    summary:
      'Работа на площадках Экспоцентра и Крокуса: встреча гостей, регистрация, навигация. Смены по календарю мероприятий.',
    responsibilities: [
      'Регистрировать участников на стойке',
      'Ориентировать гостей по площадке',
      'Помогать организаторам на площадке',
    ],
    requirements: ['Презентабельный вид', 'Чёткая речь', 'Английский приветствуется'],
    perks: ['Оплата в день мероприятия', 'Смены выбираете сами', 'Питание на площадке'],
    salaryFrom: 3800,
    salaryTo: 5500,
    salaryPeriod: 'SHIFT',
    city: 'Москва',
    district: 'Экспоцентр',
    workFormat: 'ONSITE',
    employmentType: 'PROJECT',
    shiftDays: ['WED', 'THU', 'FRI', 'SAT'],
    hoursPerWeek: 14,
    tags: ['Ивенты', 'Оплата в день смены', 'Английский'],
    isHot: true,
    isActive: true,
    publishedAt: daysAgo(1),
  },
  {
    crmId: 'CRM-1012',
    companyName: 'Агентство «Формат»',
    contactName: 'Юлия Нестерова',
    contactEmail: 'staff@format-events.ru',
    crmClientId: 'client-format',
    title: 'Промоутер-консультант',
    summary:
      'Дегустации и промо в торговых центрах. Разовые выходы или постоянный график — на ваш выбор.',
    responsibilities: [
      'Рассказывать о продукте посетителям',
      'Проводить дегустации по скрипту',
      'Заполнять отчёт по смене',
    ],
    requirements: ['От 18 лет', 'Медкнижка для продуктовых промо', 'Общительность'],
    perks: ['Выходы от 4 часов', 'Оплата через 3 дня', 'Обучение перед первой сменой'],
    salaryFrom: 400,
    salaryTo: 520,
    salaryPeriod: 'HOUR',
    city: 'Москва',
    district: null,
    workFormat: 'ONSITE',
    employmentType: 'PROJECT',
    shiftDays: ['SAT', 'SUN'],
    hoursPerWeek: 12,
    tags: ['Выходные', 'Без опыта', 'Почасовая оплата'],
    isHot: false,
    isActive: true,
    publishedAt: daysAgo(11),
  },
  {
    crmId: 'CRM-1013',
    companyName: 'Лаборатория Гагарина',
    contactName: 'Дмитрий Ильин',
    contactEmail: 'lab@gagarin-research.ru',
    crmClientId: 'client-gagarin',
    title: 'Лаборант-исследователь',
    summary:
      'Исследовательская лаборатория берёт студентов химических и биологических факультетов на подготовку образцов.',
    responsibilities: [
      'Готовить растворы и образцы',
      'Вести лабораторный журнал',
      'Обслуживать приборы по регламенту',
    ],
    requirements: [
      'Химия или биология, 2 курс и выше',
      'Аккуратность в протоколах',
      'От 16 часов в неделю',
    ],
    perks: ['Публикации в соавторстве', 'Тема для диплома', 'Свободный вход в лабораторию'],
    salaryFrom: 45000,
    salaryTo: 58000,
    salaryPeriod: 'MONTH',
    city: 'Москва',
    district: 'Ленинский проспект',
    workFormat: 'ONSITE',
    employmentType: 'PART_TIME',
    shiftDays: ['MON', 'WED', 'FRI'],
    hoursPerWeek: 18,
    tags: ['Наука', 'Диплом', 'Лаборатория'],
    isHot: false,
    isActive: true,
    publishedAt: daysAgo(7),
  },
  {
    crmId: 'CRM-1014',
    companyName: 'Технопарк «Вектор»',
    contactName: 'Лидия Ким',
    contactEmail: 'jobs@vector-tech.ru',
    crmClientId: 'client-vector',
    title: 'Аналитик данных (стажёр)',
    summary:
      'Стажировка в продуктовой аналитике: дашборды, когорты, A/B. Нужен человек, которому нравится копаться в цифрах.',
    responsibilities: [
      'Собирать выгрузки по SQL',
      'Поддерживать дашборды команды',
      'Считать метрики экспериментов',
    ],
    requirements: ['SQL уверенно', 'Python на уровне pandas', 'Статистика в объёме курса вуза'],
    perks: ['Удалённо или гибрид', 'Наставник-аналитик', 'Проект в портфолио'],
    salaryFrom: 58000,
    salaryTo: 75000,
    salaryPeriod: 'MONTH',
    city: 'Москва',
    district: null,
    workFormat: 'REMOTE',
    employmentType: 'INTERNSHIP',
    shiftDays: ['MON', 'TUE', 'WED', 'THU', 'FRI'],
    hoursPerWeek: 20,
    tags: ['Аналитика', 'SQL', 'Python'],
    isHot: true,
    isActive: true,
    publishedAt: daysAgo(3),
  },
];

/** Учётные записи для демонстрации всех трёх ролей. */
export const DEMO_CREDENTIALS = {
  student: { email: 'student@demo.ru', password: 'Demo12345!' },
  admin: { email: 'admin@fattakhov.ru', password: 'Admin12345!' },
  /** Работодатель входит по коду из CRM, а не по паролю */
  employerCode: 'SEVR-2026-DEMO',
  employerCrmClientId: 'client-sever',
} as const;

export const DEMO_STUDENT_PROFILE = {
  fullName: 'Алиса Ковалёва',
  phone: '+7 916 240-11-08',
  gender: 'FEMALE' as const,
  birthYear: 2005,
  university: 'НИУ ВШЭ',
  speciality: 'Реклама и связи с общественностью',
  studyYear: 3,
  city: 'Москва',
  workDays: ['MON', 'WED', 'FRI', 'SAT'] as const,
  hoursPerWeek: 22,
  skills: ['Excel', 'SMM', 'Английский B2', 'Копирайтинг', 'Figma'],
  about: 'Ищу подработку в маркетинге или сфере услуг. Свободна во второй половине дня.',
};

export const CONSENT_VERSION = '2026-01-15';
